name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16.x' ]
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Install Golang ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Golang Ext
        run: |
          go version;
          export GO111MODULE=off;
          $GOPATH;
          env | grep -E "GO|PATH";
          ls;
      - name: Ls
        run: ls
      - name: Go Deps
        run: |
          go get github.com/go-telegram-bot-api/telegram-bot-api;
          go get github.com/gin-gonic/gin;
      - name: Build
        run: go build main.go
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }} #95.183.55.254
          port: ${{ secrets.PORT }} #22
          username: ${{ secrets.USER }} #psh
          key: ${{ secrets.KEY }}
          source: "main,static"
          target: "/var/www/royal/backend"
  restart:
    needs: deploy
    name: "Restart Services!"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.KEY }}" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName ${{ secrets.HOST }}
            User ${{ secrets.USER }}
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END

      - name: Stop the server
        run: ssh staging 'sudo systemctl stop bukva-backend'

      - name: Start the server
        run: ssh staging 'sudo systemctl start bukva-backend'